import { z } from "zod";
import { publicProcedure, router } from "../_core/trpc";
import * as calendarDb from "../calendarDb";

/**
 * Calendar Views Router
 * User-specific calendar view configurations
 * Version 2.0 - Post-Adversarial QA
 */

export const calendarViewsRouter = router({
  // Get user's calendar views
  getViews: publicProcedure.query(async ({ ctx }) => {
    const userId = ctx.user?.id || 1;
    return await calendarDb.getUserViews(userId);
  }),

  // Get user's default view
  getDefaultView: publicProcedure.query(async ({ ctx }) => {
    const userId = ctx.user?.id || 1;
    return await calendarDb.getUserDefaultView(userId);
  }),

  // Create calendar view
  createView: publicProcedure
    .input(
      z.object({
        name: z.string().min(1).max(100),
        isDefault: z.boolean().default(false),
        filters: z.object({
          modules: z.array(z.string()).optional(),
          eventTypes: z.array(z.string()).optional(),
          statuses: z.array(z.string()).optional(),
          priorities: z.array(z.string()).optional(),
          assignedTo: z.array(z.number()).optional(),
          showAutoGenerated: z.boolean().optional(),
        }),
        defaultViewType: z
          .enum(["MONTH", "WEEK", "DAY", "AGENDA"])
          .default("MONTH"),
      })
    )
    .mutation(async ({ input, ctx }) => {
      const userId = ctx.user?.id || 1;

      // TODO: If isDefault is true, unset other default views

      return await calendarDb.createView({
        userId,
        name: input.name,
        isDefault: input.isDefault,
        filters: input.filters,
        defaultViewType: input.defaultViewType,
      });
    }),

  // Update calendar view
  updateView: publicProcedure
    .input(
      z.object({
        viewId: z.number(),
        updates: z.object({
          name: z.string().min(1).max(100).optional(),
          isDefault: z.boolean().optional(),
          filters: z
            .object({
              modules: z.array(z.string()).optional(),
              eventTypes: z.array(z.string()).optional(),
              statuses: z.array(z.string()).optional(),
              priorities: z.array(z.string()).optional(),
              assignedTo: z.array(z.number()).optional(),
              showAutoGenerated: z.boolean().optional(),
            })
            .optional(),
          defaultViewType: z
            .enum(["MONTH", "WEEK", "DAY", "AGENDA"])
            .optional(),
        }),
      })
    )
    .mutation(async ({ input, ctx }) => {
      // TODO: Verify user owns this view
      // TODO: If isDefault is true, unset other default views

      return await calendarDb.updateView(input.viewId, input.updates);
    }),

  // Delete calendar view
  deleteView: publicProcedure
    .input(z.object({ viewId: z.number() }))
    .mutation(async ({ input, ctx }) => {
      // TODO: Verify user owns this view

      return await calendarDb.deleteView(input.viewId);
    }),
});
