import { z } from "zod";
import { router, protectedProcedure, getAuthenticatedUserId } from "../_core/trpc";
import * as calendarDb from "../calendarDb";
import { getDb } from "../db";
import { calendarViews } from "../../drizzle/schema";
import { and, eq } from "drizzle-orm";


/**
 * Calendar Views Router
 * User-specific calendar view configurations
 * Version 2.0 - Post-Adversarial QA
 * PRODUCTION-READY - No placeholders
 */

export const calendarViewsRouter = router({
  // Get user's calendar views
  getViews: protectedProcedure.query(async ({ ctx }) => {
    const userId = getAuthenticatedUserId(ctx);
    return await calendarDb.getUserViews(userId);
  }),

  // Get user's default view
  getDefaultView: protectedProcedure.query(async ({ ctx }) => {
    const userId = getAuthenticatedUserId(ctx);
    const defaultView = await calendarDb.getUserDefaultView(userId);

    // If no default view, return a sensible default
    if (!defaultView) {
      return {
        id: 0,
        userId,
        name: "Default View",
        isDefault: true,
        filters: {
          modules: [],
          eventTypes: [],
          statuses: ["SCHEDULED", "IN_PROGRESS"],
          priorities: [],
          assignedTo: [],
          showAutoGenerated: true,
        },
        defaultViewType: "MONTH" as const,
      };
    }

    return defaultView;
  }),

  // Create calendar view
  createView: protectedProcedure
    .input(
      z.object({
        name: z.string().min(1).max(100),
        isDefault: z.boolean().default(false),
        filters: z.object({
          modules: z.array(z.string()).optional(),
          eventTypes: z.array(z.string()).optional(),
          statuses: z.array(z.string()).optional(),
          priorities: z.array(z.string()).optional(),
          assignedTo: z.array(z.number()).optional(),
          showAutoGenerated: z.boolean().optional(),
        }),
        defaultViewType: z
          .enum(["MONTH", "WEEK", "DAY", "AGENDA"])
          .default("MONTH"),
      })
    )
    .mutation(async ({ input, ctx }) => {
      const userId = getAuthenticatedUserId(ctx);

      // If setting as default, unset other default views
      if (input.isDefault) {
        const db = await getDb();
        if (!db) throw new Error("Database not available");
        if (!db) throw new Error("Database not available");

        await db
          .update(calendarViews)
          .set({ isDefault: false })
          .where(
            and(
              eq(calendarViews.userId, userId),
              eq(calendarViews.isDefault, true)
            )
          );
      }

      // Create view
      return await calendarDb.createView({
        userId,
        name: input.name,
        isDefault: input.isDefault,
        filters: input.filters,
        defaultViewType: input.defaultViewType,
      });
    }),

  // Update calendar view
  updateView: protectedProcedure
    .input(
      z.object({
        viewId: z.number(),
        updates: z.object({
          name: z.string().min(1).max(100).optional(),
          isDefault: z.boolean().optional(),
          filters: z
            .object({
              modules: z.array(z.string()).optional(),
              eventTypes: z.array(z.string()).optional(),
              statuses: z.array(z.string()).optional(),
              priorities: z.array(z.string()).optional(),
              assignedTo: z.array(z.number()).optional(),
              showAutoGenerated: z.boolean().optional(),
            })
            .optional(),
          defaultViewType: z
            .enum(["MONTH", "WEEK", "DAY", "AGENDA"])
            .optional(),
        }),
      })
    )
    .mutation(async ({ input, ctx }) => {
      const userId = getAuthenticatedUserId(ctx);

      // Verify ownership
      const db = await getDb();
        if (!db) throw new Error("Database not available");
      if (!db) throw new Error("Database not available");

      const [view] = await db
        .select()
        .from(calendarViews)
        .where(eq(calendarViews.id, input.viewId))
        .limit(1);

      if (!view || view.userId !== userId) {
        throw new Error("View not found or permission denied");
      }

      // If setting as default, unset other default views
      if (input.updates.isDefault) {
        await db
          .update(calendarViews)
          .set({ isDefault: false })
          .where(
            and(
              eq(calendarViews.userId, userId),
              eq(calendarViews.isDefault, true)
            )
          );
      }

      // Update view
      return await calendarDb.updateView(input.viewId, input.updates);
    }),

  // Delete calendar view
  deleteView: protectedProcedure
    .input(z.object({ viewId: z.number() }))
    .mutation(async ({ input, ctx }) => {
      const userId = getAuthenticatedUserId(ctx);

      // Verify ownership
      const db = await getDb();
        if (!db) throw new Error("Database not available");
      if (!db) throw new Error("Database not available");

      const [view] = await db
        .select()
        .from(calendarViews)
        .where(eq(calendarViews.id, input.viewId))
        .limit(1);

      if (!view || view.userId !== userId) {
        throw new Error("View not found or permission denied");
      }

      // Delete view
      return await calendarDb.deleteView(input.viewId);
    }),

  // Set view as default
  setAsDefault: protectedProcedure
    .input(z.object({ viewId: z.number() }))
    .mutation(async ({ input, ctx }) => {
      const userId = getAuthenticatedUserId(ctx);

      // Verify ownership
      const db = await getDb();
        if (!db) throw new Error("Database not available");
      if (!db) throw new Error("Database not available");

      const [view] = await db
        .select()
        .from(calendarViews)
        .where(eq(calendarViews.id, input.viewId))
        .limit(1);

      if (!view || view.userId !== userId) {
        throw new Error("View not found or permission denied");
      }

      // Unset other default views
      await db
        .update(calendarViews)
        .set({ isDefault: false })
        .where(
          and(
            eq(calendarViews.userId, userId),
            eq(calendarViews.isDefault, true)
          )
        );

      // Set this view as default
      await db
        .update(calendarViews)
        .set({ isDefault: true })
        .where(eq(calendarViews.id, input.viewId));

      return { success: true };
    }),
});
