ALTER TABLE batches ADD COLUMN version int NOT NULL DEFAULT 1;
ALTER TABLE clients ADD COLUMN version int NOT NULL DEFAULT 1;
ALTER TABLE invoices ADD COLUMN version int NOT NULL DEFAULT 1;
ALTER TABLE orders ADD COLUMN version int NOT NULL DEFAULT 1;
