-- TER-567: Rename fulfillment status PENDING -> READY_FOR_PACKING
--
-- Step 1: Expand enum to include READY_FOR_PACKING while keeping PENDING
ALTER TABLE `orders` MODIFY COLUMN `fulfillmentStatus` enum('DRAFT','CONFIRMED','PENDING','READY_FOR_PACKING','PACKED','SHIPPED','DELIVERED','RETURNED','RESTOCKED','RETURNED_TO_VENDOR','CANCELLED') DEFAULT 'READY_FOR_PACKING';
ALTER TABLE `order_status_history` MODIFY COLUMN `fulfillmentStatus` enum('DRAFT','CONFIRMED','PENDING','READY_FOR_PACKING','PACKED','SHIPPED','DELIVERED','RETURNED','RESTOCKED','RETURNED_TO_VENDOR','CANCELLED') NOT NULL DEFAULT 'READY_FOR_PACKING';
-- Step 2: Migrate existing PENDING rows to READY_FOR_PACKING
UPDATE `orders` SET `fulfillmentStatus` = 'READY_FOR_PACKING' WHERE `fulfillmentStatus` = 'PENDING';
UPDATE `order_status_history` SET `fulfillmentStatus` = 'READY_FOR_PACKING' WHERE `fulfillmentStatus` = 'PENDING';
-- Step 3: Shrink enum to remove PENDING
ALTER TABLE `orders` MODIFY COLUMN `fulfillmentStatus` enum('DRAFT','CONFIRMED','READY_FOR_PACKING','PACKED','SHIPPED','DELIVERED','RETURNED','RESTOCKED','RETURNED_TO_VENDOR','CANCELLED') DEFAULT 'READY_FOR_PACKING';
ALTER TABLE `order_status_history` MODIFY COLUMN `fulfillmentStatus` enum('DRAFT','CONFIRMED','READY_FOR_PACKING','PACKED','SHIPPED','DELIVERED','RETURNED','RESTOCKED','RETURNED_TO_VENDOR','CANCELLED') NOT NULL DEFAULT 'READY_FOR_PACKING';
