name: terp
region: nyc

databases:
  - name: terp-mysql-db
    engine: MYSQL
    production: true
    cluster_name: terp-mysql-db

services:
  - name: web
    github:
      repo: EvanTenenbaum/TERP
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile

    # Instance configuration (synced with production - Jan 26, 2026)
    # Using apps-d-1vcpu-2gb with autoscaling (2-4 instances)
    instance_size_slug: apps-d-1vcpu-2gb

    # Autoscaling configuration
    autoscaling:
      min_instance_count: 2
      max_instance_count: 4
      metrics:
        cpu:
          percent: 70

    # Health check (optimized for deployment speed - 2024-12-19)
    # Uses /health/live for liveness (no DB dependency, prevents premature restarts)
    # Server startup takes ~55s including migrations, so 60s delay is safe with margin
    health_check:
      http_path: /health/live
      initial_delay_seconds: 120 # Reduced from 180s - server ready in ~55s
      period_seconds: 15 # Reduced probe frequency to minimize noise
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 8

    # HTTP configuration
    http_port: 3000

    # Routes
    routes:
      - path: /

    # Environment variables (sensitive values should be set in DO control panel)
    envs:
      - key: NODE_ENV
        value: production
      - key: RATE_LIMIT_GET
        value: "1000"
      - key: ENABLE_RBAC
        value: "true"
      - key: ENABLE_QA_CRONS
        value: "true"
      # Memory limit for the application (in bytes)
      # apps-d-1vcpu-2gb (2GB): 1536000000 (1.5GB)
      # This value is used by memoryOptimizer.ts for accurate health reporting
      - key: NODE_MEMORY_LIMIT
        value: "1536000000"

      # Vite frontend environment variables (required for build)
      - key: VITE_APP_TITLE
        value: TERP
        scope: RUN_AND_BUILD_TIME

      - key: VITE_APP_LOGO
        value: /logo.png
        scope: RUN_AND_BUILD_TIME

      - key: VITE_APP_ID
        value: terp-app
        scope: RUN_AND_BUILD_TIME

      # Clerk authentication (using test keys - update to production keys in DO control panel)
      - key: VITE_CLERK_PUBLISHABLE_KEY
        value: pk_test_Y2xlYXItY2FyZGluYWwtNjMuY2xlcmsuYWNjb3VudHMuZGV2JA
        scope: RUN_AND_BUILD_TIME

      - key: CLERK_SECRET_KEY
        value: sk_test_gLGRGGDzMjmxvYMdxTfPuRQQeUMpvbOQkJBKBJCZBD
        scope: RUN_TIME

      # Database connection (automatically injected from linked database)
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${terp-mysql-db.DATABASE_URL}

      # Auth secrets (JWT_SECRET is required, NEXTAUTH_SECRET kept for backward compatibility)
      - key: JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      - key: NEXTAUTH_SECRET
        scope: RUN_TIME
        type: SECRET

      - key: NEXTAUTH_URL
        scope: RUN_TIME
        type: SECRET

      # Sentry (optional - set in DO control panel if using)
      - key: SENTRY_DSN
        scope: RUN_TIME
        type: SECRET

      # Cron secret (set in DO control panel)
      - key: CRON_SECRET
        scope: RUN_TIME
        type: SECRET

      # Papertrail endpoint (set in DO control panel)
      # Format: logs.papertrailapp.com:XXXXX
      - key: PAPERTRAIL_ENDPOINT
        scope: RUN_TIME
        type: SECRET

# Note: Data augmentation scripts should be run manually via:
# doctl apps create-job-run <app-id> augment-data
# The job definition has been moved to scripts/jobs/augment-data.yaml
