name: terp
region: nyc

services:
  - name: web
    github:
      repo: EvanTenenbaum/TERP
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    instance_count: 1
    instance_size_slug: basic-xs
    
    # Health check (optimized for deployment stability)
    # Uses /health/live for liveness (no DB dependency, prevents premature restarts)
    health_check:
      http_path: /health/live
      initial_delay_seconds: 90
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 5
    
    # HTTP configuration
    http_port: 3000
    
    # Routes
    routes:
      - path: /
    
    # Environment variables (sensitive values should be set in DO control panel)
    envs:
      - key: NODE_ENV
        value: production
      - key: RATE_LIMIT_GET
        value: "1000"
      - key: ENABLE_RBAC
        value: "true"
      - key: ENABLE_QA_CRONS
        value: "true"
      - key: UPLOAD_DIR
        value: /tmp/uploads
      
      # Database connection (set actual value in DO control panel)
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      
      # Auth secrets (set actual values in DO control panel)
      - key: NEXTAUTH_SECRET
        scope: RUN_TIME
        type: SECRET
      
      - key: NEXTAUTH_URL
        scope: RUN_TIME
        type: SECRET
      
      # Sentry (optional - set in DO control panel if using)
      - key: SENTRY_DSN
        scope: RUN_TIME
        type: SECRET
      
      # Cron secret (set in DO control panel)
      - key: CRON_SECRET
        scope: RUN_TIME
        type: SECRET
      
      # Papertrail endpoint (set in DO control panel)
      # Format: logs.papertrailapp.com:XXXXX
      - key: PAPERTRAIL_ENDPOINT
        scope: RUN_TIME
        type: SECRET

# Seed job removed - run manually when needed via:
# doctl apps create-job-run <app-id> <job-name>
# Or use: DATABASE_URL="..." pnpm seed:light from a local/dev environment
#
# To re-enable automatic seeding (NOT RECOMMENDED for production):
# jobs:
#   - name: seed-database
#     github:
#       repo: EvanTenenbaum/TERP
#       branch: main
#     dockerfile_path: Dockerfile
#     instance_count: 1
#     instance_size_slug: basic-xs
#     run_command: pnpm install && pnpm seed:light
#     source_dir: /
#     kind: POST_DEPLOY
#     envs:
#       - key: NODE_ENV
#         value: production
#       - key: DATABASE_URL
#         scope: RUN_TIME
#         type: SECRET
