name: terp
region: nyc

# Log forwarding configuration
# Papertrail log forwarding using Digital Ocean's native integration
# Add PAPERTRAIL_ENDPOINT environment variable in Digital Ocean console
log_destinations:
  - name: papertrail
    papertrail:
      endpoint: ${PAPERTRAIL_ENDPOINT}

services:
  - name: web
    github:
      repo: EvanTenenbaum/TERP
      branch: main
      deploy_on_push: true
    
    # Build configuration
    build_command: pnpm install --no-frozen-lockfile && pnpm run build:production
    run_command: pnpm start
    
    # Environment
    environment_slug: node-js
    
    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xs
    
    # Health check (optimized for deployment stability)
    # Uses /health/live for liveness (no DB dependency, prevents premature restarts)
    health_check:
      http_path: /health/live
      initial_delay_seconds: 90
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 5
    
    # HTTP configuration
    http_port: 3000
    
    # Routes
    routes:
      - path: /
    
    # Environment variables (sensitive values should be set in DO control panel)
    envs:
      # Build-time: Disable CI mode to allow lockfile updates during build
      # CI mode automatically enables frozen-lockfile
      - key: CI
        value: "false"
        scope: BUILD_TIME
      # Also set pnpm config as backup
      - key: PNPM_CONFIG_FROZEN_LOCKFILE
        value: "false"
        scope: BUILD_TIME
      - key: NODE_ENV
        value: production
      - key: RATE_LIMIT_GET
        value: "1000"
      - key: ENABLE_RBAC
        value: "true"
      - key: ENABLE_QA_CRONS
        value: "true"
      - key: UPLOAD_DIR
        value: /tmp/uploads
      
      # Database connection (set actual value in DO control panel)
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      
      # Auth secrets (set actual values in DO control panel)
      - key: NEXTAUTH_SECRET
        scope: RUN_TIME
        type: SECRET
      
      - key: NEXTAUTH_URL
        scope: RUN_TIME
        type: SECRET
      
      # Sentry (optional - set in DO control panel if using)
      - key: SENTRY_DSN
        scope: RUN_TIME
        type: SECRET
      
      # Cron secret (set in DO control panel)
      - key: CRON_SECRET
        scope: RUN_TIME
        type: SECRET
      
      # Papertrail endpoint (set in DO control panel)
      # Format: logs.papertrailapp.com:XXXXX
      - key: PAPERTRAIL_ENDPOINT
        scope: RUN_TIME
        type: SECRET
