# Oracle: Inventory.Strains.CreateStrain
# Create a custom strain

flow_id: "Inventory.Strains.CreateStrain"
description: "Create a new custom strain from the intake strain picker"
role: "InventoryManager"
seed_profile: "basic_sales"
tags:
  - tier2
  - inventory
  - mutation
  - strains
timeout: 30000

preconditions:
  ensure:
    - entity: "user"
      ref: "seed:user.inventory_manager"
      where:
        permissions_include: "inventory:create"

steps:
  - action: navigate
    path: "/inventory"
    wait_for: "[data-testid='inventory-table'], table"

  - action: wait
    network_idle: true
    timeout: 5000

  - action: click
    target: "[data-testid='new-batch-btn'], button:has-text('Add Batch'), button:has-text('New Batch'), a:has-text('Add Batch')"
    wait_after: 500

  - action: wait
    for: "[role='dialog']:has-text('New Product Intake'), [data-testid='batch-form'], form"
    timeout: 5000

  - action: click
    target: "[role='dialog'] button[role='combobox']:has-text('Search for a strain'), [role='dialog'] button[role='combobox']:has-text('Select strain'), [role='dialog'] button[role='combobox']:has-text('Enter strain name')"
    wait_after: 300

  - action: type
    target: "[role='dialog'] input[placeholder*='Type strain name' i]"
    value: "Purple Haze Test {{timestamp}}"
    clear_first: true

  - action: click
    target: "[cmdk-item]:has-text('Create new:'), [role='option']:has-text('Create new:')"
    wait_after: 1000

  - action: wait
    for: "[role='dialog'] button[role='combobox']:has-text('Purple Haze Test')"
    timeout: 5000

  - action: screenshot
    name: "strain_created"

expected_ui:
  visible:
    - "[role='dialog'] button[role='combobox']:has-text('Purple Haze Test')"
  text_present:
    - "Purple Haze"
  not_visible:
    - "[data-testid='error-message']"

expected_db:
  strains:
    - where:
        name_like: "Purple Haze Test%"
      expect:
        category: "sativa"
        ulid_not_null: true
        description_contains: "classic sativa"
      store_as: "created_strain"
      count: 1

  invariants:
    - name: "Strain has ULID"
      query: |
        SELECT COUNT(*) as count FROM strains
        WHERE name LIKE 'Purple Haze Test%'
          AND ulid IS NOT NULL
          AND LENGTH(ulid) = 26
      assert: "count = 1"
