# Oracle: Inventory.Strains.CreateStrain
# Create a custom strain

flow_id: "Inventory.Strains.CreateStrain"
description: "Create a new custom strain with category and optional aliases"
role: "InventoryManager"
seed_profile: "basic_sales"
tags:
  - tier2
  - inventory
  - mutation
  - strains
timeout: 30000

preconditions:
  ensure:
    - entity: "user"
      ref: "seed:user.inventory_manager"
      where:
        permissions_include: "inventory:create"

steps:
  - action: navigate
    path: "/inventory"
    wait_for: "[data-testid='inventory-table'], table"

  - action: wait
    network_idle: true
    timeout: 5000

  # Navigate to strains section - may be a tab or separate page
  - action: click
    target: "[data-testid='strains-tab'], a:has-text('Strains'), [data-testid='strains-link']"
    wait_after: 1000

  - action: wait
    for: "[data-testid='strains-list'], .strains-table, [data-testid='strains-page']"
    timeout: 5000

  - action: click
    target: "[data-testid='new-strain-btn'], button:has-text('New Strain'), button:has-text('Add Strain')"
    wait_after: 500

  - action: wait
    for: "[data-testid='strain-form'], form, .strain-modal"
    timeout: 5000

  - action: type
    target: "[data-testid='strain-name-input'], input[name='name']"
    value: "Purple Haze Test {{timestamp}}"
    clear_first: true

  - action: select
    target: "[data-testid='strain-category-select'], select[name='category']"
    value: "sativa"

  - action: type
    target: "[data-testid='strain-description-input'], textarea[name='description']"
    value: "A classic sativa strain known for its creative and euphoric effects"
    clear_first: true

  - action: type
    target: "[data-testid='strain-aliases-input'], input[name='aliases']"
    value: "Purple Haze, P Haze, PH"
    clear_first: true

  - action: click
    target: "[data-testid='submit-strain'], button[type='submit'], button:has-text('Create')"
    wait_after: 1000

  - action: wait
    network_idle: true
    timeout: 5000

  - action: screenshot
    name: "strain_created"

expected_ui:
  visible:
    - "[data-testid='success-toast'], .toast-success"
  text_present:
    - "Purple Haze"
    - "sativa"
  not_visible:
    - "[data-testid='error-message']"

expected_db:
  strains:
    - where:
        name_like: "Purple Haze Test%"
      expect:
        category: "sativa"
        ulid_not_null: true
        description_contains: "classic sativa"
      store_as: "created_strain"
      count: 1

  invariants:
    - name: "Strain has ULID"
      query: |
        SELECT COUNT(*) as count FROM strains
        WHERE name LIKE 'Purple Haze Test%'
          AND ulid IS NOT NULL
          AND LENGTH(ulid) = 26
      assert: "count = 1"
