# Oracle: Inventory.Batches.DeleteBatch
# Soft delete a batch (Super Admin only)

flow_id: "Inventory.Batches.DeleteBatch"
description: "Soft delete a batch by setting status to CLOSED (Super Admin only)"
role: "SuperAdmin"
seed_profile: "basic_sales"
tags:
  - tier2
  - inventory
  - mutation
  - destructive
timeout: 30000

preconditions:
  ensure:
    - entity: "user"
      ref: "seed:user.super_admin"
      where:
        permissions_include: "inventory:delete"
  create:
    - entity: "batch"
      ref: "test_batch_to_delete"
      data:
        sku: "DELETE-TEST-{{timestamp}}"
        batchStatus: "LIVE"
        onHandQty: "50"
        reservedQty: "0"
        quarantineQty: "0"

steps:
  - action: navigate
    path: "/inventory"
    wait_for: "[data-testid='inventory-table'], table"

  - action: wait
    network_idle: true
    timeout: 5000

  - action: type
    target: "[data-testid='inventory-search-input'], input[placeholder*='Search inventory' i]"
    value: "{{temp:test_batch_to_delete.sku}}"
    clear_first: true

  - action: wait
    for: "tr:has-text('{{temp:test_batch_to_delete.sku}}')"
    timeout: 5000

  - action: click
    target: "tr:has-text('{{temp:test_batch_to_delete.sku}}'), [data-testid='batch-row']:first-child"
    wait_after: 300

  - action: click
    target: "[data-testid='status-CLOSED'], button:has-text('Closed')"
    wait_after: 500

  - action: wait
    network_idle: true
    timeout: 5000

  - action: screenshot
    name: "batch_deleted"

expected_ui:
  visible:
    - "[data-testid='success-toast'], .toast-success"
  text_present:
    - "CLOSED"

expected_db:
  batches:
    - where:
        sku: "{{temp:test_batch_to_delete.sku}}"
      expect:
        batchStatus: "CLOSED"
        onHandQty_gte: 0
      store_as: "deleted_batch"

  auditLogs:
    - where:
        entity: "Batch"
        action_in: ["DELETE", "STATUS_CHANGE"]
        entityId: "$deleted_batch.id"
      expect:
        actorId_not_null: true
      count_gte: 1

  invariants:
    - name: "Soft delete preserves batch record"
      query: |
        SELECT COUNT(*) as count FROM batches
        WHERE id = $deleted_batch.id
      assert: "count = 1"

    - name: "Closed batch excluded from live inventory"
      query: |
        SELECT COUNT(*) as count FROM batches
        WHERE id = $deleted_batch.id
          AND batchStatus = 'LIVE'
      assert: "count = 0"
