# Oracle: Inventory.Movements.RecordMovement
# Record a manual inventory movement

flow_id: "Inventory.Movements.RecordMovement"
description: "Record an inventory movement through quantity adjustment in the inspector"
role: "InventoryManager"
seed_profile: "basic_sales"
tags:
  - tier1
  - inventory
  - mutation
  - movements
timeout: 30000

preconditions:
  ensure:
    - entity: "batch"
      ref: "seed:batch.og_kush"
      where:
        batchStatus: "LIVE"
        onHandQty_gte: 50
    - entity: "user"
      ref: "seed:user.inventory_manager"
      where:
        permissions_include: "inventory:update"

steps:
  - action: navigate
    path: "/inventory"
    wait_for: "[data-testid='inventory-table'], table"

  - action: wait
    network_idle: true
    timeout: 5000

  - action: click
    target: "tr:has-text('OG Kush'), [data-testid='batch-row']:first-child"
    wait_after: 500

  - action: wait
    for: "[data-testid='batch-detail'], .batch-detail-panel"
    timeout: 5000

  - action: click
    target: "[data-testid='adjust-qty-btn'], button:has-text('Adjust Quantity'), button:has-text('Adjust')"
    wait_after: 500

  - action: wait
    for: "[data-testid='qty-adjustment'], #qty-adjustment, [role='dialog']:has-text('Adjust Quantity')"
    timeout: 5000

  - action: type
    target: "[data-testid='qty-adjustment'], #qty-adjustment, input[id='qty-adjustment']"
    value: "-5"
    clear_first: true

  - action: type
    target: "[data-testid='qty-reason'], #qty-reason, input[id='qty-reason']"
    value: "Sample sent to buyer for quality review"
    clear_first: true

  - action: click
    target: "[data-testid='submit-adjustment'], button:has-text('Save'), button[type='submit']"
    wait_after: 1000

  - action: wait
    network_idle: true
    timeout: 5000

  - action: screenshot
    name: "movement_recorded"

expected_ui:
  visible:
    - "[data-testid='success-toast'], .toast-success"
  not_visible:
    - "[data-testid='error-message']"

expected_db:
  inventory_movements:
    - where:
        batchId: "$seed:batch.og_kush.id"
        inventoryMovementType: "SAMPLE"
      expect:
        quantityChange: "-5"
        performedBy_not_null: true
        notes_contains: "Sample sent"
      store_as: "recorded_movement"
      count_gte: 1

  invariants:
    - name: "Movement has performer"
      query: |
        SELECT COUNT(*) as count FROM inventory_movements
        WHERE batchId = $seed:batch.og_kush.id
          AND inventoryMovementType = 'SAMPLE'
          AND performedBy IS NOT NULL
      assert: "count >= 1"
