# Oracle: Inventory.Movements.ReverseMovement
# Reverse an existing inventory movement

flow_id: "Inventory.Movements.ReverseMovement"
description: "Reverse a prior movement by applying an opposite quantity adjustment"
role: "InventoryManager"
seed_profile: "basic_sales"
tags:
  - tier2
  - inventory
  - mutation
  - movements
timeout: 45000

preconditions:
  ensure:
    - entity: "batch"
      ref: "seed:batch.og_kush"
      where:
        batchStatus: "LIVE"
    - entity: "user"
      ref: "seed:user.inventory_manager"
      where:
        permissions_include: "inventory:update"

steps:
  - action: navigate
    path: "/inventory"
    wait_for: "[data-testid='inventory-table'], table"

  - action: wait
    network_idle: true
    timeout: 5000

  - action: click
    target: "tr:has-text('OG Kush'), [data-testid='batch-row']:first-child"
    wait_after: 500

  - action: wait
    for: "[data-testid='batch-detail'], .batch-detail-panel"
    timeout: 5000

  - action: click
    target: "[data-testid='adjust-qty-btn'], button:has-text('Adjust Quantity'), button:has-text('Adjust')"
    wait_after: 500

  - action: wait
    for: "[data-testid='qty-adjustment'], #qty-adjustment, [role='dialog']:has-text('Adjust Quantity')"
    timeout: 5000

  - action: type
    target: "[data-testid='qty-adjustment'], #qty-adjustment, input[id='qty-adjustment']"
    value: "10"
    clear_first: true

  - action: type
    target: "[data-testid='qty-reason'], #qty-reason, input[id='qty-reason']"
    value: "Sample returned by buyer - product did not meet requirements"
    clear_first: true

  - action: click
    target: "[data-testid='submit-adjustment'], button:has-text('Save'), button[type='submit']"
    wait_after: 1000

  - action: wait
    network_idle: true
    timeout: 5000

  - action: screenshot
    name: "movement_reversed"

expected_ui:
  visible:
    - "[data-testid='success-toast'], .toast-success"
  not_visible:
    - "[data-testid='error-message']"

expected_db:
  inventory_movements:
    - where:
        batchId: "$seed:batch.og_kush.id"
        notes_contains: "reversal test"
      expect:
        isReversed: true
      store_as: "original_movement"

    - where:
        batchId: "$seed:batch.og_kush.id"
        quantityChange: "+10"
      expect:
        notes_contains: "returned by buyer"
        reversalOfId: "$original_movement.id"
      count_gte: 1

  invariants:
    - name: "Reversal creates opposite movement"
      query: |
        SELECT
          (SELECT quantityChange FROM inventory_movements WHERE id = $original_movement.id) as original_qty,
          (SELECT quantityChange FROM inventory_movements WHERE reversalOfId = $original_movement.id) as reversal_qty
      assert: "original_qty + reversal_qty = 0"
