# Oracle: Inventory.Movements.ReverseMovement
# Reverse an existing inventory movement

flow_id: "Inventory.Movements.ReverseMovement"
description: "Reverse an existing inventory movement with full audit trail linkage"
role: "InventoryManager"
seed_profile: "basic_sales"
tags:
  - tier2
  - inventory
  - mutation
  - movements
timeout: 45000

preconditions:
  ensure:
    - entity: "batch"
      ref: "seed:batch.og_kush"
      where:
        batchStatus: "LIVE"
    - entity: "user"
      ref: "seed:user.inventory_manager"
      where:
        permissions_include: "inventory:update"
  create:
    - entity: "inventory_movement"
      ref: "temp:movement_to_reverse"
      data:
        batchId: "$seed:batch.og_kush.id"
        inventoryMovementType: "SAMPLE"
        quantityChange: "-10"
        notes: "Sample for reversal test"

steps:
  - action: navigate
    path: "/inventory"
    wait_for: "[data-testid='inventory-table'], table"

  - action: wait
    network_idle: true
    timeout: 5000

  - action: click
    target: "tr:has-text('OG Kush'), [data-testid='batch-row']:first-child"
    wait_after: 500

  - action: wait
    for: "[data-testid='batch-detail'], .batch-detail-panel"
    timeout: 5000

  - action: click
    target: "[data-testid='movements-tab'], button:has-text('Movements'), a:has-text('Movements')"
    wait_after: 500

  - action: wait
    for: "[data-testid='movement-list'], .movements-table"
    timeout: 5000

  - action: click
    target: "tr:has-text('SAMPLE'):has-text('-10') [data-testid='movement-actions'], tr:has-text('SAMPLE'):first-child button"
    wait_after: 500

  - action: click
    target: "[data-testid='reverse-movement'], button:has-text('Reverse'), [data-value='reverse']"
    wait_after: 500

  - action: wait
    for: "[data-testid='reversal-modal'], [data-testid='reason-input'], .reversal-dialog"
    timeout: 5000

  - action: type
    target: "[data-testid='reversal-reason'], textarea[name='reason'], input[name='reason']"
    value: "Sample returned by buyer - product did not meet requirements"
    clear_first: true

  - action: click
    target: "[data-testid='confirm-reversal'], button:has-text('Confirm'), button[type='submit']"
    wait_after: 1000

  - action: wait
    network_idle: true
    timeout: 5000

  - action: screenshot
    name: "movement_reversed"

expected_ui:
  visible:
    - "[data-testid='success-toast'], .toast-success"
  text_present:
    - "reversed"
  not_visible:
    - "[data-testid='error-message']"

expected_db:
  inventory_movements:
    - where:
        batchId: "$seed:batch.og_kush.id"
        notes_contains: "reversal test"
      expect:
        isReversed: true
      store_as: "original_movement"

    - where:
        batchId: "$seed:batch.og_kush.id"
        quantityChange: "+10"
      expect:
        notes_contains: "returned by buyer"
        reversalOfId: "$original_movement.id"
      count_gte: 1

  invariants:
    - name: "Reversal creates opposite movement"
      query: |
        SELECT
          (SELECT quantityChange FROM inventory_movements WHERE id = $original_movement.id) as original_qty,
          (SELECT quantityChange FROM inventory_movements WHERE reversalOfId = $original_movement.id) as reversal_qty
      assert: "original_qty + reversal_qty = 0"
