# Oracle: Inventory.Batches.UpdateBatch
# Update an existing batch's COGS and notes

flow_id: "Inventory.Batches.UpdateBatch"
description: "Update batch metadata through the edit modal from the inventory inspector"
role: "InventoryManager"
seed_profile: "basic_sales"
tags:
  - tier1
  - inventory
  - mutation
timeout: 30000

preconditions:
  ensure:
    - entity: "batch"
      ref: "seed:batch.og_kush"
      where:
        batchStatus: "LIVE"
    - entity: "user"
      ref: "seed:user.inventory_manager"
      where:
        permissions_include: "inventory:update"

steps:
  - action: navigate
    path: "/inventory"
    wait_for: "[data-testid='inventory-table'], table"

  - action: wait
    network_idle: true
    timeout: 5000

  - action: click
    target: "tr:has-text('OG Kush'), [data-testid='batch-row']:first-child"
    wait_after: 500

  - action: wait
    for: "[data-testid='batch-detail'], .batch-detail-panel"
    timeout: 5000

  - action: click
    target: "[data-testid='edit-batch-btn'], button:has-text('Edit')"
    wait_after: 500

  - action: wait
    for: "[role='dialog']:has-text('Edit Product'), [role='dialog'] form, #rack"
    timeout: 5000

  - action: type
    target: "#rack, input[id='rack']"
    value: "R2"
    clear_first: true

  - action: select
    target: "[role='dialog'] [role='combobox'], select[name='status']"
    value: "LIVE"

  - action: click
    target: "button:has-text('Update Product'), [role='dialog'] button[type='submit']"
    wait_after: 1000

  - action: wait
    network_idle: true
    timeout: 5000

  - action: screenshot
    name: "batch_updated"

expected_ui:
  visible:
    - "[data-testid='success-toast'], .toast-success"
  not_visible:
    - "[data-testid='error-message']"

expected_db:
  batches:
    - where:
        id: "$seed:batch.og_kush.id"
      expect:
        batchStatus: "LIVE"
      store_as: "updated_batch"

  audit_logs:
    - where:
        entity: "Batch"
        entityId: "$seed:batch.og_kush.id"
        action: "BATCH_UPDATE"
      expect:
        reason_contains: "Q1"
      count_gte: 1
