#!/bin/bash
# Aggregate Session Files into ACTIVE_SESSIONS.md
# Usage: ./scripts/aggregate-sessions.sh

set -e

SESSIONS_DIR="docs/sessions"
OUTPUT_FILE="docs/ACTIVE_SESSIONS.md"
TEMP_FILE="/tmp/active_sessions_temp.md"

echo "📊 Aggregating session files..."

# Start building the output file
cat > "$TEMP_FILE" << 'EOF'
# Active Claude Sessions
## Real-Time Coordination for Parallel Development

**Last Updated:** $(date '+%Y-%m-%d %I:%M %p %Z')
**Auto-Generated:** This file is automatically generated from individual session files
**Source:** `docs/sessions/active/*.md`

---

## 🟢 Currently Working

| Session ID | Task | Branch | Module | Status | Started | ETA |
|------------|------|--------|--------|--------|---------|-----|
EOF

# Process active sessions
ACTIVE_COUNT=0
if [ -d "$SESSIONS_DIR/active" ]; then
    for file in "$SESSIONS_DIR/active"/*.md; do
        if [ -f "$file" ]; then
            # Extract info from session file
            SESSION_ID=$(grep "^# Session:" "$file" | head -1 | sed 's/# Session: //')
            TASK=$(grep "^## Task:" "$file" | head -1 | sed 's/## Task: //')
            BRANCH=$(grep "^\*\*Branch:\*\*" "$file" | head -1 | sed 's/\*\*Branch:\*\* //')
            MODULE=$(grep "^\*\*Module:\*\*" "$file" | head -1 | sed 's/\*\*Module:\*\* //')
            STATUS=$(grep "^\*\*Current:\*\*" "$file" | head -1 | sed 's/\*\*Current:\*\* //')
            STARTED=$(grep "^\*\*Created:\*\*" "$file" | head -1 | sed 's/\*\*Created:\*\* //')
            ETA=$(grep "^\*\*ETA:\*\*" "$file" | head -1 | sed 's/\*\*ETA:\*\* //')

            echo "| $SESSION_ID | $TASK | $BRANCH | $MODULE | $STATUS | $STARTED | $ETA |" >> "$TEMP_FILE"
            ACTIVE_COUNT=$((ACTIVE_COUNT + 1))
        fi
    done
fi

if [ $ACTIVE_COUNT -eq 0 ]; then
    echo "| _(none)_ | - | - | - | - | - | - |" >> "$TEMP_FILE"
fi

# Add paused sessions
cat >> "$TEMP_FILE" << 'EOF'

## ⏸️ Paused / Waiting

| Session ID | Task | Branch | Reason | Paused At | Resume When |
|------------|------|--------|--------|-----------|-------------|
EOF

# Process paused sessions (placeholder for now)
echo "| _(none)_ | - | - | - | - | - |" >> "$TEMP_FILE"

# Add completed sessions (today)
cat >> "$TEMP_FILE" << 'EOF'

## ✅ Completed Today

| Session ID | Task | Branch | Merged At | Commit |
|------------|------|--------|-----------|--------|
EOF

# Process completed sessions
COMPLETED_COUNT=0
if [ -d "$SESSIONS_DIR/completed" ]; then
    TODAY=$(date '+%Y-%m-%d')
    for file in "$SESSIONS_DIR/completed"/*$TODAY*.md; do
        if [ -f "$file" ]; then
            SESSION_ID=$(grep "^# Session:" "$file" | head -1 | sed 's/# Session: //')
            TASK=$(grep "^## Task:" "$file" | head -1 | sed 's/## Task: //')
            BRANCH=$(grep "^\*\*Branch:\*\*" "$file" | head -1 | sed 's/\*\*Branch:\*\* //')
            COMMIT=$(grep "^\*\*Last Commit:\*\*" "$file" | head -1 | awk '{print $NF}')

            echo "| $SESSION_ID | $TASK | $BRANCH | Pending Approval | $COMMIT |" >> "$TEMP_FILE"
            COMPLETED_COUNT=$((COMPLETED_COUNT + 1))
        fi
    done
fi

if [ $COMPLETED_COUNT -eq 0 ]; then
    echo "| _(none)_ | - | - | - | - |" >> "$TEMP_FILE"
fi

# Add blocked sessions
cat >> "$TEMP_FILE" << 'EOF'

## 🔴 Blocked

| Session ID | Task | Branch | Blocked By | Since | Action Needed |
|------------|------|--------|------------|-------|---------------|
| _(none)_ | - | - | - | - | - |

---

## 📋 Session Assignment Rules

[... rest of the template ...]

---

**Note:** This file is auto-generated. To see detailed status for a session, check:
- Active: `docs/sessions/active/Session-[ID].md`
- Completed: `docs/sessions/completed/Session-[ID].md`
- Abandoned: `docs/sessions/abandoned/Session-[ID].md`

**To manually regenerate:** `./scripts/aggregate-sessions.sh`

EOF

# Replace the output file
mv "$TEMP_FILE" "$OUTPUT_FILE"

echo "✅ Generated $OUTPUT_FILE"
echo "📊 Summary:"
echo "  - Active sessions: $ACTIVE_COUNT"
echo "  - Completed today: $COMPLETED_COUNT"
echo "  - Total: $((ACTIVE_COUNT + COMPLETED_COUNT))"

# Optionally commit the changes
if [ "$1" == "--commit" ]; then
    echo "📝 Committing changes..."
    git add "$OUTPUT_FILE"
    git commit -m "chore: auto-update ACTIVE_SESSIONS.md from session files" || echo "No changes to commit"
fi
