#!/usr/bin/env bash
# TER-193: Auto-generate test coverage map from actual test suite
# Replaces the stale manual TEST_COVERAGE_MAP.md
set -euo pipefail

OUTPUT="${1:-docs/roadmaps/TEST_COVERAGE_MAP.md}"
TIMESTAMP=$(date -Iseconds)

# Count test files and tests per module
count_tests() {
  local pattern="$1"
  local dir="${2:-.}"
  find "$dir" -name "*.test.ts" -o -name "*.test.tsx" -o -name "*.spec.ts" 2>/dev/null | grep -i "$pattern" | wc -l | tr -d ' '
}

count_e2e() {
  local pattern="$1"
  find tests-e2e -name "*.spec.ts" 2>/dev/null | grep -i "$pattern" | wc -l | tr -d ' '
}

# Unit test counts
UNIT_TOTAL=$(find server client/src -name "*.test.ts" -o -name "*.test.tsx" 2>/dev/null | wc -l | tr -d ' ')
UNIT_SERVER=$(find server -name "*.test.ts" 2>/dev/null | wc -l | tr -d ' ')
UNIT_CLIENT=$(find client/src -name "*.test.ts" -o -name "*.test.tsx" 2>/dev/null | wc -l | tr -d ' ')

# E2E test counts
E2E_TOTAL=$(find tests-e2e -name "*.spec.ts" 2>/dev/null | wc -l | tr -d ' ')
E2E_CRITICAL=$(find tests-e2e/critical-paths -name "*.spec.ts" 2>/dev/null | wc -l | tr -d ' ')
E2E_GOLDEN=$(find tests-e2e/golden-flows -name "*.spec.ts" 2>/dev/null | wc -l | tr -d ' ')
E2E_RBAC=$(find tests-e2e/rbac -name "*.spec.ts" 2>/dev/null | wc -l | tr -d ' ')

# Module-level counts
INV_UNIT=$(count_tests "inventor" server)
INV_E2E=$(count_e2e "inventor\|intake")
ORD_UNIT=$(count_tests "order" server)
ORD_E2E=$(count_e2e "order\|sales")
ACCT_UNIT=$(count_tests "account\|credit\|cogs\|gl\|ledger" server)
ACCT_E2E=$(count_e2e "account\|credit\|payment")
AUTH_UNIT=$(count_tests "auth\|login\|session" server)
AUTH_E2E=$(count_e2e "auth\|login\|rbac")
DASH_UNIT=$(count_tests "dashboard" "client/src")
DASH_E2E=$(count_e2e "dashboard")
DB_UNIT=$(count_tests "Db\|schema\|migration\|seed" server)

# Integration tests
INTEGRATION_TOTAL=$(find tests/integration -name "*.test.ts" 2>/dev/null | wc -l | tr -d ' ')

# Status indicator
status_for() {
  local count=$1
  if [ "$count" -ge 5 ]; then echo "🟢";
  elif [ "$count" -ge 1 ]; then echo "🟡";
  else echo "🔴"; fi
}

cat > "$OUTPUT" << HEREDOC
# TERP Test Coverage Map

**Last Updated:** ${TIMESTAMP} (Auto-generated by \`scripts/generate-coverage-map.sh\`)
**Source of Truth:** This file is generated from the actual test suite — do not edit manually.

---

## Test Suite Summary

| Metric | Count |
|---|---|
| Unit test files (server) | ${UNIT_SERVER} |
| Unit test files (client) | ${UNIT_CLIENT} |
| Integration test files | ${INTEGRATION_TOTAL} |
| E2E test files | ${E2E_TOTAL} |
| E2E critical-paths | ${E2E_CRITICAL} |
| E2E golden-flows | ${E2E_GOLDEN} |
| E2E RBAC suites | ${E2E_RBAC} |
| **Total test files** | **$((UNIT_TOTAL + INTEGRATION_TOTAL + E2E_TOTAL))** |

---

## Coverage by Module

| Module | Unit Tests | E2E Tests | Status |
|---|---|---|---|
| Inventory | ${INV_UNIT} files | ${INV_E2E} files | $(status_for $((INV_UNIT + INV_E2E))) |
| Orders/Sales | ${ORD_UNIT} files | ${ORD_E2E} files | $(status_for $((ORD_UNIT + ORD_E2E))) |
| Accounting | ${ACCT_UNIT} files | ${ACCT_E2E} files | $(status_for $((ACCT_UNIT + ACCT_E2E))) |
| Auth/RBAC | ${AUTH_UNIT} files | ${AUTH_E2E} files | $(status_for $((AUTH_UNIT + AUTH_E2E))) |
| Dashboard | ${DASH_UNIT} files | ${DASH_E2E} files | $(status_for $((DASH_UNIT + DASH_E2E))) |
| Database Layer | ${DB_UNIT} files | — | $(status_for ${DB_UNIT}) |

---

## E2E Critical Path Coverage

| Suite | Files | Purpose |
|---|---|---|
HEREDOC

# List critical path specs
for f in tests-e2e/critical-paths/*.spec.ts; do
  name=$(basename "$f" .spec.ts | sed 's/-/ /g; s/\b\(.\)/\u\1/g')
  echo "| ${name} | \`$(basename "$f")\` | Critical path |" >> "$OUTPUT"
done

cat >> "$OUTPUT" << HEREDOC

---

## Staleness Guard

This file must be regenerated on CI. If the timestamp above is older than 7 days,
run \`bash scripts/generate-coverage-map.sh\` to refresh.

To add to CI, include this step after tests:
\`\`\`yaml
- name: Generate coverage map
  run: bash scripts/generate-coverage-map.sh
\`\`\`
HEREDOC

echo "Coverage map generated at ${OUTPUT}"
